### PR TITLE
added function to convert 2 factor y to 0,1

### PR DESCRIPTION
**Pull request by JackStat**
This code changes causes a number of issues and is not ready for a merge with master.  I am just confused why it is tripping this error 

```
Some terminal node predictions were excessively large for Bernoulli and have been capped at 1.0. Likely due to a feature that separates the 0/1 outcomes. Consider reducing shrinkage parameter.
```

See discussion on #6

### CODE REVIEW

**Comment by JackStat** [comment]
I think this one is ready unless someone has some suggested modifications

**Comment by pdmetcalfe** [comment]
Please can we have some documentation of what it now does to two-level factors?

**Comment by JackStat** [comment]
There is a new function called checkY that checks for a y that is a factor with 2 levels.  If it is then it converts it to a binary.  The old y (factor) is kept and then placed inside of the data matrix in the gbm object as y. A test was added to verify that it is returning the same relative importances as the numeric y version.

I am happy to document this in the package if that is what you meant.

It may be cleaner to move some of the distribution checks into checkY as well

**Comment by pdmetcalfe** [comment]
Yup. Can you stick something describing the user-visible functionality in
the roxygen?

pdm

**Comment by JackStat** [comment]
Docs added closes #6

**Pull request merged**
