### PR TITLE
R front end

### PR DESCRIPTION
**Pull request by jhickeyPhysics**
RFrontEnd with more testing and new API - gbmt and gbmt_fit.
Fix for RNGScope seg fault in C++ also included.

### CODE REVIEW

**Comment by pdmetcalfe** [comment]
Couple of comments.

For the moment, could you remove the warning on the old API; that'll be for the next version.

To make the tests work, would it be enough to move `test-basics-old-api.r` to `test-old-api.r` ?

**Comment by jhickeyPhysics** [comment]
Hi Paul,

I'll remove the warning and that is not a bad idea!

Best wishes,

James

**Comment by pdmetcalfe** [comment]
Wow - what happened to the code coverage!?

**Comment by jhickeyPhysics** [comment]
Coveralls is flaky at times.  We jumped from 42 to 66% without really adding much tests.  We haven't removed tests, have removed R code and added tests to functions previously not tested.
I am looking at codecov.io and am getting a similar reading but it shows the hits/misses.  The calculation is definitely wrong - for example the gbm_more function has 0% coverage despite having a lot of tests associated with it, another is it suggests that gbm_plot in the C++ is never called despite again having many calls in testthat.

Additional tests that should be added just to boost coverage -
Testing functionality runs successfully for all distributions.

**Pull request merged**
