### PR TITLE
fold.id

### PR DESCRIPTION
**Pull request by DexGroves**
See https://github.com/harrysouthworth/gbm/pull/42

### CODE REVIEW

**Comment by pdmetcalfe** [comment]
Could you please add some appropriate unit tests for this functionality, so we know it works and doesn't get broken in the future?

Thanks!

**Comment by pdmetcalfe** [comment]
Also - please document the fold.id parameter.

**Comment by DexGroves** [comment]
Never used testthat until now. Let me know if I missed a spot.

**Comment by pdmetcalfe** [comment]
Cheers!

I think we need `@param fold.id <stuff>` somewhere in `gbm.R`, so that the documentation will automatically rebuild when we rerun roxygen?

**Comment by DexGroves** [comment]
How's that boss?

**Comment by pdmetcalfe** [comment]
Beautiful! Thanks. :gift:

**Pull request merged**
